// <auto-generated />
namespace ProyectoFinal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cambioModeloCoordenadas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambioModeloCoordenadas));
        
        string IMigrationMetadata.Id
        {
            get { return "201404282037031_cambioModeloCoordenadas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
