// <auto-generated />
namespace ProyectoFinal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class asdqwefad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asdqwefad));
        
        string IMigrationMetadata.Id
        {
            get { return "201404301936182_asdqwefad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
