// <auto-generated />
namespace ProyectoFinal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class klk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(klk));
        
        string IMigrationMetadata.Id
        {
            get { return "201404300712332_klk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
