// <auto-generated />
namespace ProyectoFinal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class agregueFotosCreadoPor1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregueFotosCreadoPor1));
        
        string IMigrationMetadata.Id
        {
            get { return "201402260555060_agregueFotosCreadoPor1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
