// <auto-generated />
namespace ProyectoFinal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class agreguecoordernadas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agreguecoordernadas));
        
        string IMigrationMetadata.Id
        {
            get { return "201404222353138_agreguecoordernadas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
